import NextAuthProvider from "@/app/NextAuthProvider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { SiteNavigation } from "../components/navigations/SiteNav";
import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <NextAuthProvider>
        <body className={inter.className}>
          <SiteNavigation />
          {children}
        </body>
      </NextAuthProvider>
    </html>
  );
}
