import NextAuthProvider from "@/app/(site)/NextAuthProvider";
import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import { Inter } from "next/font/google";
import { SiteNavigation } from "../components/navigations/SiteNav";
import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Future",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <NextAuthProvider>
        <ThemeProvider attribute="class" defaultTheme="system">
          <body className={inter.className}>
            <SiteNavigation />
            <main className="p-20">{children}</main>
          </body>
        </ThemeProvider>
      </NextAuthProvider>
    </html>
  );
}
