export const ArrayGenres = [
    { id: 1, name: "Science Fiction" },
    { id: 2, name: "Fantasy" },
    { id: 3, name: "Mystery" },
    { id: 4, name: "Thriller" },
    { id: 5, name: "Romance" },
    { id: 6, name: "Historical Fiction" },
    { id: 7, name: "Biography" },
    { id: 8, name: "Self Help" },
    { id: 9, name: "Non-Fiction" },
    { id: 10, name: "Horror" },
    { id: 11, name: "Young Adult" },
    { id: 12, name: "Children's" },
    { id: 13, name: "Classics" },
    { id: 14, name: "Adventure" },
    { id: 15, name: "Dystopian" },
    { id: 16, name: "Poetry" },
    { id: 17, name: "Graphic Novel" },
    { id: 18, name: "Literary Fiction" },
    { id: 19, name: "Crime" },
    { id: 20, name: "Cookbook" },
];
